### ISSUE TITLE
How are you doing? Why have you stopped work on your project?

### ISSUE THREAD

**Issue by cipher387** [dmw94/bazzellpy#43]

**Comment by dmw94** [comment]
Dear cipher387, 

I am all good thanks, and I hope you are too!

This project isn't abandoned - i've been working on a gnarly problem for work that is absorbing all my time currently. I hope to address the open issues soon once i've got a bit more capacity.

Please accept my apologies for the delay in addressing the user stories you've raised -

With best wishes,

dmw94

**Comment by cipher387** [comment]
I think even if you give this project just 15 minutes of time a day, after a few weeks you'll make a lot of progress.

Good luck with your work tasks!
